# Generated by Django 5.0.4 on 2026-03-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composeapp',
            name='compose_file',
            field=models.CharField(default='docker-compose.yml', help_text='Chemin relatif vers le fichier compose dans le repo', max_length=500),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='domain',
            field=models.CharField(blank=True, help_text='Domaine associé à ce projet', max_length=253),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='env_vars',
            field=models.JSONField(default=dict, help_text="Variables d'environnement injectées dans le .env avant docker compose up"),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='github_repo',
            field=models.CharField(help_text='owner/repo', max_length=500),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='name',
            field=models.CharField(help_text='Nom affiché dans le dashboard', max_length=100),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='project_dir',
            field=models.CharField(blank=True, help_text='Répertoire où le repo est cloné sur le serveur', max_length=500),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='status',
            field=models.CharField(choices=[('idle', 'Idle'), ('cloning', 'Clonage du dépôt...'), ('building', 'Build en cours...'), ('starting', 'Démarrage...'), ('running', 'En cours'), ('stopped', 'Arrêté'), ('error', 'Erreur')], default='idle', max_length=20),
        ),
        migrations.AlterField(
            model_name='composeapp',
            name='status_message',
            field=models.TextField(blank=True, help_text="Dernier message de log ou d'erreur"),
        ),
    ]
