# Generated by Django 5.0.4 on 2026-03-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stacks', '0002_alter_composeapp_compose_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NginxVhost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_label', models.CharField(default='app', max_length=50)),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('upstream_port', models.IntegerField(help_text="Port exposé sur l'hôte par le container applicatif")),
                ('ssl_enabled', models.BooleanField(default=False)),
                ('ssl_email', models.EmailField(blank=True, max_length=254)),
                ('ssl_status', models.CharField(choices=[('none', 'Pas de SSL'), ('pending', 'Obtention en cours'), ('active', 'SSL actif'), ('error', "Erreur d'obtention"), ('expired', 'Certificat expiré')], default='none', max_length=20)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('certbot_output', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vhosts', to='stacks.composeapp')),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
