# Generated by Django 5.0.4 on 2026-03-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxvhost',
            name='container_name',
            field=models.CharField(blank=True, help_text='Nom du container Docker sélectionné lors de la création (référence)', max_length=255),
        ),
    ]
